name: Generated APK AAB (Upload - Create Artifact To Github Action)

on:
  push:
    tags:
      - v*

  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Create Secrets file
        run: |
          echo "Creating file with interpolated secrets"
          cat <<EOF > ./app/src/main/java/com/viscouspot/gitsync/Secrets.kt
          package com.viscouspot.gitsync
  
          object Secrets {
              const val GIT_CLIENT_ID = "${{ secrets.GIT_CLIENT_ID }}"
              const val GIT_CLIENT_SECRET = "${{ secrets.GIT_CLIENT_SECRET }}"
          }
          EOF
        
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

    # #1     
    #   - name: Decode Keystore
    #     env:
    #       ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
    #       RELEASE_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}

    #     run: |
    #       echo $ENCODED_STRING > keystore-b64.txt
    #       cat keystore-b64.txt | base64 -d > $RELEASE_KEYSTORE_PATH
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      #2
      - name: Build Release APKs
        run: |
          bash ./gradlew assembleBaseRelease
          bash ./gradlew assembleAll-files-variantRelease

      - name: Build Release Bundles
        run: |
          bash ./gradlew bundleBaseRelease
          bash ./gradlew bundleAll-files-variantRelease

      - name: Move files
        run: |
          mv app/base/release/app-base-release.apk app/release/app-base-release.apk
          mv app/base/release/app-base-release.aab app/release/app-base-release.aab
          mv app/all-files-variant/release/app-all-files-variant-release.apk app/release/app-all-files-variant-release.apk
          mv app/all-files-variant/release/app-all-files-variant-release.aab app/release/app-all-files-variant-release.aab
          
      - name: Sign App
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs
          signingKey: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.RELEASE_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
      #3
      # - name: Upload Release Build to Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-artifacts
      #     paths: |
      #       app/base/release/
      #       app/all-files-variant/release/
      # #4      
      # - name: Create Github Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     prerelease: true
      #     files: |
      #       app/base/release/app-release.apk
      #       app/all-files-variant/release/app-release.aab
